# Gemini AI Model Configuration
model_name: "gemini-2.0-flash"  # Model name for Gemini AI
generation_config:
  temperature: 0.9
  top_p: 1
  top_k: 1
  max_output_tokens: 2048
safety_settings:
  - category: "HARM_CATEGORY_HARASSMENT"
    threshold: "BLOCK_MEDIUM_AND_ABOVE"
  - category: "HARM_CATEGORY_HATE_SPEECH"
    threshold: "BLOCK_MEDIUM_AND_ABOVE"
  - category: "HARM_CATEGORY_SEXUALLY_EXPLICIT"
    threshold: "BLOCK_MEDIUM_AND_ABOVE"
  - category: "HARM_CATEGORY_DANGEROUS_CONTENT"
    threshold: "BLOCK_MEDIUM_AND_ABOVE"